project:
  type: website
  output-dir: docs

website:
  title: "Damie Pak"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd
      - text: Blog
        href: posts.qmd
  page-footer: 
     background: dark
     right: Copyright 2024, Damie Pak

format:
  html:
    theme: styles.scss
    css: styles.scss
    toc: true
    page-layout: full
    mainfont: Jost

editor: visual

