project:
  type: website
  output-dir: docs

website:
  google-analytics: "G-MHG2CQ3TR2"
  title: "Damie Pak"
  navbar:
    right:
      - about.qmd
      - research.qmd
      - text: Blog
        href: posts.qmd
      - text: "{{< iconify academicons:google-scholar-square size=32px >}}"
        href: "https://scholar.google.com/citations?user=oyKiTqgAAAAJ&hl=en"
  page-footer: 
     background: dark
     right: Copyright 2024, Damie Pak

format:
  html:
    theme: styles.scss
    css: styles.scss
    toc: true
    page-layout: full
    mainfont: Jost

editor: visual

