project:
  type: website
  output-dir: docs

website:
  title: "Damie Pak"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - posts.qmd
  page-footer: 
     background: dark
     right: Copyright 2024, Damie Pak

format:
  html:
    theme: listera
    css: styles.css
    toc: true
    page-layout: full
    mainfont: Jost

editor: visual

